DROP TABLE IF EXISTS USUARIO;
CREATE TABLE USUARIO(
    ID_USUARIO INT AUTO_INCREMENT  PRIMARY KEY,
    NOME VARCHAR(70) NOT NULL,
    LOGIN VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(200) NOT NULL UNIQUE,
    SENHA VARCHAR(50) NOT NULL,
    IDADE INT NOT NULL
);

DROP TABLE IF EXISTS BIRD;
CREATE TABLE BIRD(
    ID_BIRD INT AUTO_INCREMENT  PRIMARY KEY,
    NOME_CIENTIFICO VARCHAR(70) NOT NULL
);

DROP TABLE IF EXISTS BIRD_WATCH;
CREATE TABLE BIRD_WATCH(
    ID_BIRD_WATCH INT AUTO_INCREMENT  PRIMARY KEY,
    ID_BIRD INT NOT NULL,
    ID_USUARIO INT NOT NULL,
    NOME VARCHAR(70) NOT NULL,
    REGIAO VARCHAR(50) NOT NULL,
    COMPORTAMENTO VARCHAR(200) NOT NULL,
    ESTACAO VARCHAR(50) NOT NULL
);

ALTER TABLE BIRD_WATCH ADD CONSTRAINT FK_BIRD FOREIGN KEY (ID_BIRD) REFERENCES BIRD (ID_BIRD);
ALTER TABLE BIRD_WATCH ADD CONSTRAINT FK_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO);

DROP TABLE IF EXISTS IMAGE;
CREATE TABLE IMAGE(
    ID_IMAGE INT AUTO_INCREMENT PRIMARY KEY,
    IMAGEM_PATH VARCHAR(200) NOT NULL
);

DROP TABLE IF EXISTS BIRD_WATCH_IMAGE;
CREATE TABLE BIRD_WATCH_IMAGE(
    ID_IMAGE INT NOT NULL,
    ID_BIRD_WATCH INT NOT NULL,
    LATITUDE FLOAT NOT NULL,
    LONGITUDE FLOAT NOT NULL,
    DATA_CRIACAO DATE NOT NULL
);

ALTER TABLE BIRD_WATCH_IMAGE ADD CONSTRAINT FK_IMAGE FOREIGN KEY (ID_IMAGE) REFERENCES IMAGE (ID_IMAGE);
ALTER TABLE BIRD_WATCH_IMAGE ADD CONSTRAINT FK_BIRD_WATCH FOREIGN KEY (ID_BIRD_WATCH) REFERENCES BIRD_WATCH (ID_BIRD_WATCH);
